### ISSUE TITLE
Jan 19th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#16]
# Regulation Innovation SIG
## Date
Jan 19th 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Abhishek Chatterjee / Tookitai
- Christopher Trepel
- Ffion Acland / GS
- Jo Ann Barefoot / AIR
- Matt van Buskirk / Hummingbird
- Mukund Umalkar / ING
- Nicolas Decouttere 
- Peter Bouda
- Richard Maton
- Taniem Choudhoury / DB

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review [**action items from Jan 5th meeting**](https://github.com/finos/open-regtech-sig/issues/14)
- [x] Approve past meeting minutes: [Dec 8th, 2020](https://github.com/finos/open-regtech-sig/issues/13) and [Jan 5th 2021](https://github.com/finos/open-regtech-sig/issues/14) - _meeting minutes were approved_
- [x] Presentations / Demos
    - [x] David Ehrich (AIR) - Crypto Tech Sprint
    - [x] Abhishek Chatterjee (Tookitaki) - Federated AML Knowledge Base
    - [x] Matt van Buskirk (Hummingbird Regtech) 
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] open action item from January 5th meeting: Taniem Choudhury (DB) to start a thread (either on GitHub or via open-regtech-sig@finos.org) to gather a list of relevant regulations & regulators 
- [ ] open action item from January 5th meeting: ALL to contribute specific use cases around building ontologies
- [ ] open action item from January 5th meeting: David Ehrich (AIR) & FINOS to create and circulate an overview document with brief descriptions of projects/ tools presented at Reg SIG meetings to date (see https://github.com/finos/open-regtech-sig/issues/17)

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by adds68** [comment]
:wave:

**Comment by jpmsrh** [comment]
Hi

**Comment by stephengoldbaum** [comment]
Present

**Comment by anelledavis** [comment]
Here

**Comment by toshaellison** [comment]
Present

**Comment by jim-h-wang** [comment]
Present

**Comment by agitana** [comment]
hi

**Comment by ffionwiggins** [comment]
present
