### ISSUE TITLE
June 1st 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#29]
# Regulation Innovation SIG
## Date
Jun 01 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Craig Rowe / Cantor Fitzgerald
- James Nicholls / Braithwate
- Nigel Cobb / Regnosys
- Rob Winchester / CDM Smith
- Sarah Sinclair / Change Gap

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes: 
    - [x] [May 4th Reg SIG meeting](https://github.com/finos/open-regtech-sig/issues/25) -_meeting minutes were approved_
    - [x] [May 13th "FDC3 for RegTech" deep-dive](https://github.com/finos/open-regtech-sig/issues/27) - _meeting minutes were approved_
    - [x] [May 18th "Regulatory Taxonomy and Ontology" project proposal deep-dive](https://github.com/finos/open-regtech-sig/issues/28) - _meeting minutes were approved_
- [x] Regulatory Taxonomy and Ontology project proposal update (James Nicholls & Sarah Sinclair)
- [x] AIR Accelerator update (Randy Repka)
- [x] New collaboration use case proposal: AML & Quantum Computing (Ivan Radovanovic)
- [x] Next month: update on FDC3 for RegTech update 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by Ivan-Radovanovic** [comment]
hi 
thank you for this opportunity
idea around Fin crime and fraud in general with specialty review some type of activities that's going under radar and hard to win in next step with filing for arbitration with Visa or Mastercard and other special new "soon mast be" reported all crypto activities 
Fraud area is to big and banks already have products in place but some new ideas are always good for refresh 
and Quantum computing that's near future happening right now (be ready) 
thank you for taking time about this topics

**Comment by RichardWagener365** [comment]
Hi all, Richard Wagener - Codethink

**Comment by jgavronsky** [comment]
Jane here

**Comment by agitana** [comment]
hi!

**Comment by gyehuda** [comment]
Hi all, Gi here, "lurking" on the call to keep up with the conversation. I work at U.S. Bank.

**Comment by toshaellison** [comment]
Here! (Tosha Ellison, FINOS)

**Comment by Ivan-Radovanovic** [comment]
hello all

**Comment by ericaddy1** [comment]
Hello

**Comment by TLATER** [comment]
Belated, sorry, was grabbing water o/

**Comment by stephengoldbaum** [comment]
hi

**Comment by nilscluzel** [comment]
hello

**Comment by Taniem100** [comment]
Hi - signing in
